mod colors;
mod dimensions;

// Re-export everything with the same visibility as the original constants.rs.
// Items that were `pub(super)` in the original file (visible to wizard_tower/)
// are re-exported as `pub(super)` here (visible to wizard_tower/ via the
// `mod constants;` declaration in wizard_tower/mod.rs).
// Items that were `pub(crate)` are re-exported as `pub(crate)`.

// --- colors ---
pub(crate) use colors::{
    ACTIVE_TAB_BG, ACTIVE_TAB_BORDER, AFFINITY_COLOR, BACKGROUND_COLOR, COMPLETED_COLOR, DETAIL_BG,
    DETAIL_BORDER, DISABLED_TAB_BG, DISABLED_TAB_BORDER, DISABLED_TAB_TEXT, GRAPH_AREA_BG,
    GRAPH_EDGE_COLOR, GRAPH_EDGE_LOCKED_COLOR, GRAPH_NODE_BG, GRAPH_NODE_BORDER,
    GRAPH_NODE_COMPLETED_BORDER, GRAPH_NODE_FREE_BORDER, GRAPH_NODE_LOCKED_BG,
    GRAPH_NODE_LOCKED_BORDER, GRAPH_NODE_SELECTED_BORDER, INACTIVE_TAB_BG, INSIGHT_ANCHOR_BORDER,
    INSIGHT_COLOR, INSIGHT_EDGE_COLOR, INSIGHT_NODE_BG, INSIGHT_NODE_BORDER,
    INSIGHT_NODE_MAXED_BORDER, INSIGHT_PROGRESS_FILL, LOCKED_TEXT_COLOR, PENDING_COLOR,
    PROGRESS_BAR_FILL, RUNE_COLOR, SECTION_BG, SLIDER_FILL_COLOR, SLIDER_HANDLE_COLOR,
    SLIDER_TRACK_BG, SLIDER_TRACK_BORDER, STAT_LABEL_COLOR, STAT_SECTION_COLOR, TAB_BORDER,
    TALENT_ACTIVE_BG, TALENT_ACTIVE_BORDER, TALENT_BAR_BG, TALENT_BAR_FILL, TALENT_LOCKED_BG,
    TALENT_LOCKED_BORDER, TALENT_UNLOCKED_BG, TALENT_UNLOCKED_BORDER, TEXT_COLOR,
    TIME_TRAVEL_BOSS_COLOR, TIME_TRAVEL_HOVER_BG, TIME_TRAVEL_SECTION_BG,
    TIME_TRAVEL_SECTION_BORDER, TIME_TRAVEL_SELECTED_BG, TIME_TRAVEL_SELECTED_TEXT, TITLE_COLOR,
};

// --- dimensions ---
pub(crate) use dimensions::{
    ALLOC_ADJUST_BUTTON_STYLE, ALLOC_ADJUST_STEP, BACK_BUTTON_STYLE, BUTTON_STYLE, COLUMN_GAP,
    COMMIT_BUTTON_STYLE, DESC_SHRINK_THRESHOLD, DETAIL_PANEL_PADDING, DETAIL_PANEL_WIDTH,
    DETAIL_SMALL_FONT_SIZE, DETAIL_TEXT_FONT_SIZE, DETAIL_TITLE_FONT_SIZE, GRAPH_ANIMATION_SPEED,
    GRAPH_DEFAULT_SCALE, GRAPH_EDGE_AVOIDANCE_MARGIN, GRAPH_EDGE_CURVE_SEGMENTS,
    GRAPH_EDGE_THICKNESS, GRAPH_FREE_NODE_SIZE, GRAPH_NODE_SIZE, GRAPH_ZOOM_MAX, GRAPH_ZOOM_MIN,
    GRAPH_ZOOM_SPEED, INSIGHT_ANCHOR_SIZE, INSIGHT_CONSTELLATION_OFFSET, INSIGHT_FONT_SIZE,
    INSIGHT_NODE_RADIUS, INSIGHT_NODE_SIZE, LEFT_PANEL_PERCENT, LEVEL_FONT_SIZE, MARGIN_SMALL,
    RIGHT_PANEL_PERCENT, RUNE_OPACITY, RUNE_TEXT_ALPHA, RUNE_TEXT_SIZE, SECTION_PADDING,
    SLIDER_HANDLE_HEIGHT, SLIDER_HANDLE_WIDTH, SLIDER_TRACK_HEIGHT, SLIDER_TRACK_WIDTH,
    SPELL_ICON_SIZE, START_TIME_TRAVEL_BUTTON_STYLE, STAT_SECTION_FONT_SIZE, STAT_VALUE_FONT_SIZE,
    SWITCH_WIZARD_BUTTON_STYLE, TAB_FONT_SIZE, TAB_HEIGHT, TAB_PADDING_H, TALENT_BAR_WIDTH,
    TALENT_CARD_FONT, TALENT_CARD_GAP, TALENT_CARD_HEIGHT, TALENT_CARD_WIDTH, TALENT_DESC_FONT,
    TALENT_DESC_FONT_SMALL, TALENT_TIER_LABEL_FONT, TIME_TRAVEL_LEVEL_FONT_SIZE,
    TIME_TRAVEL_LEVEL_HEIGHT, TIME_TRAVEL_LIST_MAX_HEIGHT, TITLE_FONT_SIZE,
};

// pub(crate) items — must remain pub(crate) at this level too
pub(crate) use dimensions::NO_SELECTION_PLACEHOLDER;
pub(crate) use dimensions::spawn_coop_gated_button;

// cfg-gated item
#[cfg(debug_assertions)]
pub(crate) use dimensions::DEBUG_BUTTON_STYLE;
